title:            13protons
description:      Web Design and Development in Detroit

host: localhost
port: 3030
baseurl: "/13protons"

layouts:      _layouts

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Detroit
markdown:    kramdown

future:      true
show_drafts: false
limit_posts: 0

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

exclude: ["examples", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "gulpfile.js", "*.less", "img_source"]
